./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyPointPush1-v0 --seed 1
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyPointPush1-v0 --seed 11
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyPointPush1-v0 --seed 111
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyPointPush1-v0 --seed 1111
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyPointPush1-v0 --seed 11111
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyPointGoal1-v0 --seed 1
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyPointGoal1-v0 --seed 11
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyPointGoal1-v0 --seed 111
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyPointGoal1-v0 --seed 1111
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyPointGoal1-v0 --seed 11111
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyRacecarCircle1-v0 --seed 11111
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyRacecarCircle1-v0 --seed 1111
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyRacecarCircle1-v0 --seed 111
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyRacecarCircle1-v0 --seed 11
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyRacecarCircle1-v0 --seed 1
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyCarButton1-v0 --seed 1
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyCarButton1-v0 --seed 11
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyCarButton1-v0 --seed 111
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyCarButton1-v0 --seed 1111
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyCarButton1-v0 --seed 11111
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyHopperVelocity-v1 --seed 1
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyHopperVelocity-v1 --seed 11
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyHopperVelocity-v1 --seed 111
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyHopperVelocity-v1 --seed 1111
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyHopperVelocity-v1 --seed 11111
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyHumanoidVelocity-v1 --seed 1
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyHumanoidVelocity-v1 --seed 11
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyHumanoidVelocity-v1 --seed 111
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyHumanoidVelocity-v1 --seed 1111
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyHumanoidVelocity-v1 --seed 11111
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyHalfCheetahVelocity-v1 --seed 1
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyHalfCheetahVelocity-v1 --seed 11
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyHalfCheetahVelocity-v1 --seed 111
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyHalfCheetahVelocity-v1 --seed 1111
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyHalfCheetahVelocity-v1 --seed 11111
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyAntVelocity-v1 --seed 1
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyAntVelocity-v1 --seed 11
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyAntVelocity-v1 --seed 111
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyAntVelocity-v1 --seed 1111
./mpcdf/submit_container.sh python as_sac.py --cost-lambda-start 0 --cost-lambda-end 0 --alive-reward 0 --exp-name sac --env-id SafetyAntVelocity-v1 --seed 11111
