./mpcdf/submit_container.sh python as_sac.py --env-id SafetyPointPush1-v0 --seed 1
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyPointPush1-v0 --seed 11
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyPointPush1-v0 --seed 111
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyPointPush1-v0 --seed 1111
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyPointPush1-v0 --seed 11111
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyPointGoal1-v0 --seed 1
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyPointGoal1-v0 --seed 11
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyPointGoal1-v0 --seed 111
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyPointGoal1-v0 --seed 1111
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyPointGoal1-v0 --seed 11111
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyRacecarCircle1-v0 --seed 11111
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyRacecarCircle1-v0 --seed 1111
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyRacecarCircle1-v0 --seed 111
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyRacecarCircle1-v0 --seed 11
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyRacecarCircle1-v0 --seed 1
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyCarButton1-v0 --seed 1
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyCarButton1-v0 --seed 11
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyCarButton1-v0 --seed 111
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyCarButton1-v0 --seed 1111
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyCarButton1-v0 --seed 11111
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyHopperVelocity-v1 --seed 1
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyHopperVelocity-v1 --seed 11
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyHopperVelocity-v1 --seed 111
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyHopperVelocity-v1 --seed 1111
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyHopperVelocity-v1 --seed 11111
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyHumanoidVelocity-v1 --seed 1
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyHumanoidVelocity-v1 --seed 11
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyHumanoidVelocity-v1 --seed 111
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyHumanoidVelocity-v1 --seed 1111
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyHumanoidVelocity-v1 --seed 11111
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyHalfCheetahVelocity-v1 --seed 1
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyHalfCheetahVelocity-v1 --seed 11
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyHalfCheetahVelocity-v1 --seed 111
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyHalfCheetahVelocity-v1 --seed 1111
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyHalfCheetahVelocity-v1 --seed 11111
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyAntVelocity-v1 --seed 1
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyAntVelocity-v1 --seed 11
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyAntVelocity-v1 --seed 111
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyAntVelocity-v1 --seed 1111
./mpcdf/submit_container.sh python as_sac.py --env-id SafetyAntVelocity-v1 --seed 11111
